#!/bin/bash

### BEGIN INIT INFO
# Provides:          midea2lox
# Required-Start:    $all
# Required-Stop::    $all
# Should-Start:      $all
# Should-Stop:       $all
# Default-Start:
# Default-Stop:      0 1 6
# Short-Description: Start midea2lox at boot time
# Description:       Manage the midea2lox daemon, bridge between Midea-Cloud and Loxberry.
### END INIT INFO

#set -e
#set -u
#${DEBIAN_SCRIPT_DEBUG:+ set -v -x}


is_running() {
	/bin/ps -C "broadlink-therm" -opid= > /dev/null 2>&1
}

. /lib/lsb/init-functions
case "$1" in
        'start')
                if is_running; then
                    PID=`/bin/ps -C "broadlink-therm" -opid=`
                    echo "broadlink-thermostat is already running. PID: $PID"
                else
                    echo "Starting broadlink-thermostat.."
                if [ $EUID -eq 0 ]; then
                    cd REPLACELBPDATADIR
                    su loxberry -c ./broadlink-thermostat.py > /dev/null 2>&1 &
                    sleep 1
                else
                    cd REPLACELBPDATADIR
                    ./broadlink-thermostat.py > /dev/null 2>&1 &
                    sleep 1
                fi
                fi;;
        'stop')
                killall broadlink-therm;;
        'restart')
                $0 stop
                if is_running; then
                    echo "Unable to stop broadlink-thermostat, will not try to restart."
                    exit 1
                fi
                $0 start
                ;;
        '')
                $0 start
                ;;
        'status')
                if is_running; then
                    PID=`/bin/ps -C "broadlink-therm" -opid=`
                    echo "broadlink-thermostat is running. PID: $PID"
                else
                    echo "broadlink-thermostat is stopped."
                    exit 1
                fi;;
        *)
                echo "usage $0 start|stop|restart|status" ;;
				
esac

exit 0
